import type { PageRuntime, Runtime } from './types';

export async function loadLegacyRuntime(): Promise<{ runtime: Runtime; pages: PageRuntime }> {
  const [
    storeModule,
    routerModule,
    sidebarModule,
    timerModule,
    notificationsModule,
    commandPaletteModule,
    learningStoreModule,
    landingPageModule,
    authPageModule,
    onboardingPageModule,
    dashboardPageModule,
    sheetsPageModule,
    sqlTrackPageModule,
    problemsPageModule,
    problemDetailPageModule,
    companiesPageModule,
    companyDetailPageModule,
    roadmapPageModule,
    conceptMapPageModule,
    revisionPageModule,
    profilePageModule,
    learnHubPageModule,
    learnSubjectPageModule,
    learnTopicPageModule,
    learnSubtopicPageModule,
    learnLessonPageModule,
    interviewHubPageModule,
    interviewQuestionsPageModule,
    interviewPracticePageModule,
    mockSessionPageModule,
    debuggerHubPageModule,
    schedulerDashboardPageModule,
    analyticsDashboardPageModule,
  ] = await Promise.all([
    import('../../../store.js'),
    import('../../../router.js'),
    import('../../../components/sidebar.js'),
    import('../../../components/timer.js'),
    import('../../../components/notifications.js'),
    import('../../../components/command-palette.js'),
    import('store'),
    import('../../../pages/landing.js'),
    import('../../../pages/auth.js'),
    import('../../../pages/onboarding.js'),
    import('../../../pages/dashboard.js'),
    import('../../../pages/sheets.js'),
    import('../../../pages/sql-track.js'),
    import('../../../pages/problems.js'),
    import('../../../pages/problem-detail.js'),
    import('../../../pages/companies.js'),
    import('../../../pages/company-detail.js'),
    import('../../../pages/roadmap.js'),
    import('../../../pages/concept-map.js'),
    import('../../../pages/revision.js'),
    import('../../../pages/profile.js'),
    import('../../../pages/learn-hub.js'),
    import('../../../pages/subject-page.js'),
    import('../../../pages/topic-page.js'),
    import('../../../pages/subtopic-view.js'),
    import('../../../pages/learn-lesson.js'),
    import('../../../pages/interview-hub.js'),
    import('../../../pages/interview-questions.js'),
    import('../../../pages/interview-practice.js'),
    import('../../../pages/mock-session.js'),
    import('../../../pages/debugger-hub.js'),
    import('../../../pages/scheduler-dashboard.js'),
    import('../../../pages/analytics-dashboard.js'),
  ]);

  const runtime: Runtime = {
    store: storeModule.default,
    legacyRouter: routerModule.router,
    renderSidebar: sidebarModule.renderSidebar,
    initTimer: timerModule.initTimer,
    showToast: notificationsModule.showToast,
    initCommandPalette: commandPaletteModule.initCommandPalette,
    learningStore: learningStoreModule.default,
  };

  const pages: PageRuntime = {
    landing: { renderPage: landingPageModule.renderLanding, initPage: landingPageModule.initLanding },
    auth: { renderPage: authPageModule.renderAuth, initPage: authPageModule.initAuth },
    onboarding: { renderPage: onboardingPageModule.renderOnboarding, initPage: onboardingPageModule.initOnboarding },
    dashboard: { renderPage: dashboardPageModule.renderDashboard, initPage: dashboardPageModule.initDashboard },
    sheets: { renderPage: sheetsPageModule.renderSheets, initPage: sheetsPageModule.initSheets },
    sqlTrack: { renderPage: sqlTrackPageModule.renderSqlTrack, initPage: sqlTrackPageModule.initSqlTrack },
    problems: { renderPage: problemsPageModule.renderProblems, initPage: problemsPageModule.initProblems },
    problemDetail: { renderPage: problemDetailPageModule.renderProblemDetail, initPage: problemDetailPageModule.initProblemDetail },
    companies: { renderPage: companiesPageModule.renderCompanies, initPage: companiesPageModule.initCompanies },
    companyDetail: { renderPage: companyDetailPageModule.renderCompanyDetail, initPage: companyDetailPageModule.initCompanyDetail },
    roadmap: { renderPage: roadmapPageModule.renderRoadmap, initPage: roadmapPageModule.initRoadmap },
    conceptMap: { renderPage: conceptMapPageModule.renderConceptMap, initPage: conceptMapPageModule.initConceptMap },
    revision: { renderPage: revisionPageModule.renderRevision, initPage: revisionPageModule.initRevision },
    revisionTopic: { renderPage: revisionPageModule.renderRevision, initPage: revisionPageModule.initRevision },
    profile: { renderPage: profilePageModule.renderProfile, initPage: profilePageModule.initProfile },
    learnHub: { renderPage: learnHubPageModule.renderLearnHub, initPage: learnHubPageModule.initLearnHub },
    learnSubject: { renderPage: learnSubjectPageModule.renderSubjectPage, initPage: learnSubjectPageModule.initSubjectPage },
    learnTopic: { renderPage: learnTopicPageModule.renderTopicPage, initPage: learnTopicPageModule.initTopicPage },
    learnSubtopic: { renderPage: learnSubtopicPageModule.renderSubtopicView, initPage: learnSubtopicPageModule.initSubtopicView },
    learnLesson: { renderPage: learnLessonPageModule.renderLearnLesson, initPage: learnLessonPageModule.initLearnLesson },
    interviewHub: { renderPage: interviewHubPageModule.renderInterviewHub, initPage: interviewHubPageModule.initInterviewHub },
    interviewQuestions: { renderPage: interviewQuestionsPageModule.renderInterviewQuestions, initPage: interviewQuestionsPageModule.initInterviewQuestions },
    interviewPractice: { renderPage: interviewPracticePageModule.renderInterviewPractice, initPage: interviewPracticePageModule.initInterviewPractice },
    interviewMockSession: { renderPage: mockSessionPageModule.renderMockSession, initPage: mockSessionPageModule.initMockSession },
    debuggerHub: { renderPage: debuggerHubPageModule.renderDebuggerHub, initPage: debuggerHubPageModule.initDebuggerHub },
    schedulerDashboard: { renderPage: schedulerDashboardPageModule.renderSchedulerDashboard, initPage: schedulerDashboardPageModule.initSchedulerDashboard },
    analyticsDashboard: { renderPage: analyticsDashboardPageModule.renderAnalyticsDashboard, initPage: analyticsDashboardPageModule.initAnalyticsDashboard },
  };

  return { runtime, pages };
}

